# Generated by Django 5.1.4 on 2024-12-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
