# Generated by Django 5.1.4 on 2024-12-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_class_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined_classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='backend.class'),
        ),
    ]
