# Generated by Django 5.1.3 on 2025-01-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_activity_description_activity_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
